// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SabemiTec.Api.Data;

#nullable disable

namespace SabemiTec.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SabemiTec.Api.Models.EventoLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdContrato")
                        .HasColumnType("text");

                    b.Property<string>("IdTransacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MensagemErro")
                        .HasColumnType("text");

                    b.Property<string>("PayloadBruto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecebidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusProcessamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusRecebido")
                        .HasColumnType("text");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdTransacao")
                        .IsUnique();

                    b.ToTable("EventosLog");
                });

            modelBuilder.Entity("SabemiTec.Api.Models.StatusContrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdContrato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusAtual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UltimaDataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UltimoIdTransacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UltimoValor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdContrato")
                        .IsUnique();

                    b.ToTable("StatusContratos");
                });
#pragma warning restore 612, 618
        }
    }
}
